# Generated by Django 5.1.7 on 2025-03-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment',
            field=models.CharField(choices=[('09:00', '9:00 AM - 10:00 AM'), ('10:00', '10:00 AM - 11:00 AM'), ('11:00', '11:00 AM - 12:00 PM'), ('12:00', '12:00 PM - 1:00 PM'), ('01:00', '1:00 PM - 2:00 PM'), ('02:00', '2:00 PM - 3:00 PM'), ('03:00', '3:00 PM - 4:00 PM'), ('04:00', '4:00 PM - 5:00 PM'), ('05:00', '5:00 PM - 6:00 PM'), ('06:00', '6:00 PM - 7:00 PM')], default='09:00', max_length=20),
        ),
    ]
